configtx/application_test.go, configtx/capabilities_test.go, configtx/config_test.go, configtx/consortiums_test.go, configtx/example_test.go, configtx/msp.go, configtx/msp_test.go, configtx/orderer_test.go, configtx/organization_test.go, configtx/policies_test.go
- Bug fix
Remove SigningIdentity from MSP type because the SigningIdentity is not supposed to be updatable during channel config transactions
[FAB-17833](https://jira.hyperledger.org/browse/FAB-17833)
=> [FAB-17833] Remove SigningIdentity type from MSP type

configtx/application.go, configtx/orderer.go, configtx/organization.go, configtx/organization_test.go
- Bug fix
- anchor peers are added to only application orgs
- endpoints are added to only orderer orgs
- anchor peers and endpoints are not added to consortium orgs
[FAB-17836](https://jira.hyperledger.org/browse/FAB-17836)
=> [FAB-17836] Add newOrdererOrgConfigGroup and newApplicationOrgConfigGroup

configtx/msp.go, configtx/msp_test.go
- Bug fix
Declare FabricNodeOUs instead of initializing to ensure the proto value is nil
=> when FabricNodeOUs proto should be nil when unset

configtx/config.go, configtx/config_test.go, configtx/example_test.go, configtx/signer.go, configtx/signer_test.go
- New feature
- Improvement (improvement to code, performance, etc)
First commit:
- Support returning an unsigned config update envelope
- Refactor signing identity (SignConfigUpdate -> CreateConfigSignature and SignConfigUpdateEnvelope -> SIgnEnvelope)
Second commit:
- Refactor NewCreateChannelTx to return a config update, which allows us to utilize the signing functionality in the library.
[FAB-17871](https://jira.hyperledger.org/browse/FAB-17871)
[FAB-17872](https://jira.hyperledger.org/browse/FAB-17872)
=> Envelope and signing improvements

configtx/config.go, configtx/config_test.go
- New feature
Reintroduce retrieval functions to ensure we have a way to sanity check that the config matches what we expect when submitting an update using the fabric-config library.
[FAB-17894](https://jira.hyperledger.org/browse/FAB-17894)
=> Reintroduce original and updated config retrieval funcs

configtx/config.go, configtx/config_test.go, configtx/constants.go, configtx/example_test.go, configtx/orderer.go, configtx/orderer_test.go
* Remove the concept of top level OrdererAddresses as a field that can
be modified/updated or set when creating a new system channel genesis
block
* Introduce requirement that orderer orgs must have orderer endpoints
defined when creating a new system channel genesis block
https://jira.hyperledger.org/browse/FAB-17949
=> [FAB-17949] Remove constraint on expecting orderer endpoints to exist at the org level when updating a config

configtx/signer.go, configtx/signer_test.go, go.mod, go.sum
- Bug fix
In order to be valid signatures in the context of fabric's BCCSP functions, ECDSA signatures should be on the hash (digest) of the message. Fabric currently supports only SHA-256.
[FAB-17947](https://jira.hyperledger.org/browse/FAB-17947)
=> Signatures should be over hash of message

configtx/orderer.go, configtx/orderer_test.go
Missed this in the last PR for removing constraints on the orderer endpoints. Apparently there was another check we do when retrieving orderer org configuration that I missed originally.
=> [FAB-17949] Remove org level constraint when retrieving orderer org configuration for requiring orderer endpoints to exist

configtx/config.go, configtx/config_test.go, configtx/example_test.go, configtx/signer.go, configtx/signer_test.go
- Bug fix
Due to the non-deterministic nature of proto.Marshal, the configtx library should marshal the config update once and pass the marshaled bytes around for signatures. This particularly causes problems with updates involving AnchorPeers, hence the specific unit test verifying signatures for an anchor peer update envelope.
[FAB-17959](https://jira.hyperledger.org/browse/FAB-17959)
=> Only proto.Marshal ConfigUpdate once to ensure signatures are valid

configtx/channel.go, configtx/channel_test.go, configtx/constants.go
- New feature
Implement removal of orderer addresses from the top level of a new ConfigTx's channel group to remove the legacy config value.
[FAB-17950](https://jira.hyperledger.org/browse/FAB-17950)
=> [FAB-17950] Implement removal of orderer endpoints from toplevel channel

configtx/example_test.go, configtx/orderer.go, configtx/orderer_test.go, go.mod
Signed-off-by: Arturo Cabre <arturo@ibm.com>
- New feature
Added a function to remove KafkaBrokers from Orderer config. Useful when migrating to Raft. 
https://jira.hyperledger.org/browse/FAB-18047
=> [FAB-18047] Implement kafka brokers removal function

configtx/internal/policydsl/policyparser.go, configtx/orderer.go
This patch replaces wrong comments on `OrdererType` options with the correct constants `ConsensusTypeSolo`, `ConsensusTypeKafka` and `ConsensusTypeEtcdRaft`.
Also, this patch includes a minor fix to pass lint checks.
- Bug fix
Currently, the OrdererType options are described in the comments in `configtx/orderer.go` as follows:
```
// OrdererType is the type of orderer
// Options: `Solo`, `Kafka` or `Raft
```
These `Solo`, `Kafka` or `Raft` don’t seem to be the correct strings to give to OrdererType.
In fact, configtx lib raises an error like when the above strings are given.
This patch replaces the wrong comments on `OrdererType` options with the correct constants `ConsensusTypeSolo`, `ConsensusTypeKafka` and `ConsensusTypeEtcdRaft` to avoid misunderstanding by users.
- …
=> [FAB-18262] Fix wrong comments on OrdererType options

configtx/application.go, configtx/application_test.go
This patch allows Config Transaction Library to load cb.Config which does not contain any values for ACLs.
- Bug fix
Currently, ConfigTx Library gives errors when reading `cb.Config` which does not contain values for ACLs.
Example of error:
```
config does not contain value for ACLs
retrieving application acls: config does not contain value for ACLs
```
On the other hand, In the actual Fabric channel settings, ACLs may not be set.
This is because the default value is used if it is not set.
- e.g., fabric-samples/test-network does not set ACLs (refer to configtx.yaml).
- ConfigTx Library seems to be able to create ConfigTX with empty ACLs.
So, this patch allows Config Transaction Library to load cb.Config which does not contain any values for ACLs.
- …
=> [FAB-18264] Allow cb.Config with no ACLs to be loaded

configtx/application.go, configtx/application_test.go, configtx/channel.go, configtx/channel_test.go, configtx/consortiums.go, configtx/consortiums_test.go, configtx/orderer.go, configtx/orderer_test.go, configtx/policies.go
This patch adds SetPolicies() to easily replace multiple policies for groups and orgs in an existing configuration with the given policies.
- New feature
- Test update
This patch adds SetPolicies() to easily replace multiple policies for groups and orgs in an existing configuration with the given policies.
Targets to add the new functions:
- ApplicationGroup
- ApplicationOrg
- ChannelGroup
- ConsortiumOrg
- OrdererGroup
- OrdererOrg
By providing functions to replace multiple policies in bulk, users can change multiple policies with a single function call, so users should not need a tedious method (e.g., repeat SetPolicy() and RemovePolicy() for a group to be replaced).
As preparation for supporting SetPolicies() for groups and orgs, this patch modifies setPolicies() in …
=> [FAB-18268] Add SetPolicies() to easily replace multiple policies in an existing configuration with the given policies

configtx/example_test.go
This patch adds an example to show the bulk replacement of multiple policies by using SetPolicies().
- Test update
- Documentation update
This patch adds an example to show the bulk replacement of multiple policies by using SetPolicies().
- https://jira.hyperledger.org/browse/FAB-18271
- https://jira.hyperledger.org/browse/FAB-18268
=> [FAB-18271] Add an example for SetPolicies()

configtx/msp.go, configtx/msp_test.go
Signed-off-by: Tiffany Harris <tiffany.harris@ibm.com>
- New feature
validates TLS intermediate certs against the TLS root certs using the x509.Verify()
[FAB-18099](https://jira.hyperledger.org/browse/FAB-18099)
=> [FAB-18099] Validate TLS intermediate certs against TLS root certs

configtx/application.go, configtx/application_test.go, configtx/channel.go, configtx/channel_test.go, configtx/config.go, configtx/config_test.go, configtx/consortiums.go, configtx/consortiums_test.go, configtx/example_test.go, configtx/orderer.go, configtx/orderer_test.go, configtx/organization.go, configtx/policies.go, configtx/policies_test.go
- New feature
Added support for mod policies in config groups: Application, ApplicationOrg, Channel, ConsortiumOrg, Orderer, OrdererOrg. Previous implementation wasn't able to set mod policies which is beneficial when creating production grade custom channel configurations.
The previous code was setting mod policies to `AdminModPolicyKey` by default. This behavior was retained so when the mod policy is not set manually it is automatically set to `AdminModPolicyKey`.
There are two incompatible changes in methods `SetPolicy` and `SetPolicies` which omit first parameter called `modPolicy` because it's not needed anymore. There is a new field `ModPolicy` in `Policy` struct instead of it.
Those changes were tested in a production grade Fabric environment.
=> Added support for mod policies

configtx/application.go
Resolves #49 If the node has more than one anchor peer, it will return before all existent peers have been added again to existingAnchorPeers
Signed-off-by: Ernesto Olivier <ernesto.olivier@nexplore.com>
- Bug fix
When the RemoveAnchorPeer function is called, it just loops over the Anchor Peers and compare it with the one that it is requested to be deleted, if the current doesn't match it is added again to the config using a new array called existingAnchorPeers. 
So far so good but then there is a return statement inside the loop that it is preventing to add more than one Peer to existingAnchorPeers array.
This PR just remove that return to enable to fill the existingAnchorPeers array with all remaining Anchor Peers.
My motivation is basically that I am using this function and is not …
=> Remove a return statement to be able to add more than one peer in the existingAnchorPeers array

configtx/orderer.go, configtx/orderer/orderer.go, configtx/orderer_test.go
- Bug fix
- Test update
I removed Kafka as it is not supported as a consensus type, by mark as a deprecated Kafka's fields and functions. I also blocked the option to add configuration to an orderer with Kafka as a consensus type.
I fixed tests that had a bug and tests that need to fit to our new requirements.
issue #3513 in Fabric
=> remove kafka and fix tests

configtx/config_test.go, configtx/consortiums_test.go, configtx/msp_test.go, configtx/orderer.go, configtx/orderer/orderer.go, configtx/orderer_test.go
- Test update
This PR aims to remove solo as a consensus type. 
Tests were fixed accordingly.
Issue #4496 in fabric repo.
=> remove solo as a consensus type
