hyperledger/fabric-config

- .github/settings.yml
Update to the repo description
[FAB-17640](https://jira.hyperledger.org/browse/FAB-17640)
> [FAB-17640] Update repo description for hyperledger/fabric-config

- configtx/config.go
- configtx/orderer/orderer.go
Signed-off-by: Brett Logan <brett.t.logan@ibm.com>
> Fix vetting errors

- configtx/consortiums.go
- configtx/consortiums_test.go
- configtx/example_test.go
- New feature
Support adding a new consortium to a consortiums group.
[FAB-17813](https://jira.hyperledger.org/browse/FAB-17813)
> [FAB-17813] Implement function to set consortium

- configtx/application.go
- configtx/config.go
- configtx/config_test.go
- configtx/orderer.go
- configtx/organization.go
- configtx/policies.go
- configtx/policies_test.go
- Improvement (improvement to code, performance, etc)
For consistency with the public functions.
> Rename private addPolicy functions to setPolicy

- .github/workflows/trigger.yml
Uses same /ci-run command as Fabric
> Add github actions workflows for triggering CI from PRs

- configtx/example_test.go
- configtx/msp.go
- configtx/msp_test.go
- configtx/orderer.go
Signed-off-by: xu wu <wuxu1103@163.com>
- Bug fix
We should check any nil values from pem.Decode, otherwise it will panic when attempting to parse the bytes.
https://jira.hyperledger.org/browse/FAB-17810
> [FAB-17810] Check nil return from pem.Decode

- configtx/example_test.go
- configtx/msp.go
- configtx/msp_test.go
- Bug fix
Skip setting NodeOUs when not specified in MSP configuration 
[FAB-17835](https://jira.hyperledger.org/browse/FAB-17835
)
> [FAB-17835] Skip NodeOUs when unspecified in the channel config

- configtx/config.go
- configtx/config_test.go
- configtx/orderer.go
- Bug fix
Adds missing System Channel creation values
> Add HashingAlgorithmValue and BlockDataHashingStructureValue

- README.md
Signed-off-by: Danny Cao <dcao@us.ibm.com>
> Add godoc badge to README

- protolator/integration/integration_test.go
* TestConfigUpdate wasn't actually properly unmarshalling the config
block from testdata
> Small improvements to protolator integration test

- configtx/application.go
- configtx/application_test.go
- configtx/config.go
- configtx/config_test.go
- New feature
Add function to create an application channel genesis block.
[FAB-18027](https://jira.hyperledger.org/browse/FAB-18027)
> Add function to create an application channel genesis block

- configtx/orderer.go
- configtx/orderer_test.go
- New feature
Implementing add and remove consenters functionality to etcdraft orderer configuration
[FAB-18048](https://jira.hyperledger.org/browse/FAB-18048)
> [FAB-18048] Implement addition and removal of consenters from etcdraft

- configtx/orderer.go
- configtx/orderer_test.go
- New feature
Implements individual Orderer values updates instead of cloning and modifying the current configuration first. 
[FAB-18062](https://jira.hyperledger.org/browse/FAB-18062)
> [FAB-18062] Add support for individual Orderer value updates

- configtx/application.go
- configtx/application_test.go
- configtx/consortiums.go
- configtx/consortiums_test.go
- configtx/example_test.go
- configtx/msp.go
- configtx/msp_test.go
- configtx/orderer.go
- configtx/orderer_test.go
- configtx/signer_test.go
- New feature
Support individual MSP updates for orderer organization
[FAB-18063](https://jira.hyperledger.org/browse/FAB-18063)
> Support individual MSP updates for orderer organization

- configtx/example_test.go
- Documentation update
Showcase a few individual orderer value updates
[FAB-18092](https://jira.hyperledger.org/browse/FAB-18092)
> [FAB-18092] Add example for individual orderer value updates

- configtx/channel_test.go
This patch increases UT coverage for configtx/channel.go from 81.0% to 96.6%.
- Test update
This patch increases UT coverage for configtx/channel.go from 81.0% to 96.6%.
> Improve UT coverage for channel.go

- configtx/example_test.go
- Test update
- Documentation update
This patch adds an example for NewApplicationChannelGenesisBlock.
This patch also fixes minor typos.
- https://jira.hyperledger.org/browse/FAB-18281
> [FAB-18281] Add an example for NewApplicationChannelGenesisBlock

- .github/settings.yml
- ci/azure-pipelines.yml
Update "master" branch references to "main".
Signed-off-by: David Enyeart <enyeart@us.ibm.com>
> Update "master" branch references to "main"

- ci/azure-pipelines.yml
Update Go to 1.16.7.
Signed-off-by: David Enyeart <enyeart@us.ibm.com>
> Update Go to 1.16.7

- protolator/protoext/ordererext/configuration.go
Signed-off-by: arkadi.piven@ibm.com
- Bug fix
Add support to fabric smartbft protos parsing.
Add support for "Orderers" and BFT "Options" parsing from binary to json. #57
> Added support to fabric smartbft protos.

- .github/workflows/build.yaml
- go.mod
- go.sum
Bump to golang.org/x/net v0.23.0
> Bump to golang.org/x/net v0.23.0
